import { type Metadata } from "next";

const metadata: Metadata = {
  title: "Home | Next MDX Blog Template",
  description: "A blog template built with Next.js and MDX.",
  referrer: "origin",
  keywords: [
    "framework",
    "blog",
    "news",
    "technology",
  ],

  metadataBase: new URL(
    process.env.NODE_ENV === "production"
      ? "https://next-mdx-blog-template.vercel.app"
      : "http://localhost:8080"
  ),

  openGraph: {
    type: "website",
    description: "Generated by create next app",
    title: "Home | Create Next App",
    siteName: "Create Next App",
    url: "https://next-mdx-blog-template.vercel.app",
    locale: "en_US",
    images: [
      {
        url: "/twitter-card.png",
        width: 1200,
        height: 630,
        alt: "Create Next App",
      },
    ],
  },

  twitter: {
    card: "summary_large_image",
    title: "Home | Create Next App",
    description: "Generated by create next app",
    images: [{
      url: "/twitter-card.png",
      width: 1200,
      height: 630,
      alt: "Create Next App",
    }],
  }
};

export default metadata;
